/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zoloskivrtapp.view;

import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import zoloskivrtapp.controller.ObradaDjelatnik;
import zoloskivrtapp.model.Djelatnik;
import zoloskivrtapp.util.ZooException;

/**
 *
 * @author Igor
 */
public class ProzorDjelatnici extends javax.swing.JFrame {

    private ObradaDjelatnik obradaD;
    private DjelatnikPregled dp;
    private DjelatnikPromjena dpr;
    /**
     * Creates new form ProzorDjelatnici
     */
    public ProzorDjelatnici() {
        initComponents();
        obradaD = new ObradaDjelatnik();
        setTitle("Djelatnici");
        txtPretragaD.requestFocus();
    }
    
      public ProzorDjelatnici(DjelatnikPregled dp) {
        initComponents();
        obradaD = new ObradaDjelatnik();
        this.dp = dp;
        setTitle("Djelatnici");
        txtPretragaD.requestFocus();
    }
      
      public ProzorDjelatnici(DjelatnikPromjena dpr) {
        initComponents();
        obradaD = new ObradaDjelatnik();
        this.dpr = dpr;
        setTitle("Djelatnici");
        txtPretragaD.requestFocus();
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPretragaD = new javax.swing.JTextField();
        btnPretragaD = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListaD = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        btnPregledD = new javax.swing.JButton();
        btnIzmjenaD = new javax.swing.JButton();
        btnUnosD = new javax.swing.JButton();
        btnBrisanje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtPretragaD.setBackground(new java.awt.Color(207, 214, 221));
        txtPretragaD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPretragaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaDActionPerformed(evt);
            }
        });
        txtPretragaD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPretragaDKeyPressed(evt);
            }
        });

        btnPretragaD.setBackground(new java.awt.Color(255, 255, 0));
        btnPretragaD.setText(" 🔍");
        btnPretragaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaDActionPerformed(evt);
            }
        });

        lstListaD.setBackground(new java.awt.Color(207, 214, 221));
        lstListaD.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstListaD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lstListaD.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstListaDValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstListaD);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Povratak na izbornik");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPregledD.setBackground(new java.awt.Color(255, 255, 0));
        btnPregledD.setText("Pregled");
        btnPregledD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledDActionPerformed(evt);
            }
        });

        btnIzmjenaD.setBackground(new java.awt.Color(255, 255, 0));
        btnIzmjenaD.setText("Izmjena ");
        btnIzmjenaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjenaDActionPerformed(evt);
            }
        });

        btnUnosD.setBackground(new java.awt.Color(255, 255, 0));
        btnUnosD.setText("Unos");
        btnUnosD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosDActionPerformed(evt);
            }
        });

        btnBrisanje.setBackground(new java.awt.Color(255, 255, 0));
        btnBrisanje.setText("Brisanje");
        btnBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(txtPretragaD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPretragaD, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPregledD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmjenaD, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUnosD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrisanje, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPretragaD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPretragaD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPregledD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmjenaD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnosD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrisanje, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPretragaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPretragaDActionPerformed

    private void txtPretragaDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaDKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            ucitajDjelatnike();
        }
    }//GEN-LAST:event_txtPretragaDKeyPressed

    private void btnPretragaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaDActionPerformed
        ucitajDjelatnike();
    }//GEN-LAST:event_btnPretragaDActionPerformed

    private void lstListaDValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListaDValueChanged
         if(evt.getValueIsAdjusting()){
            return;
        }
        if(lstListaD.getSelectedValue()==null){
            return;
        }
    }//GEN-LAST:event_lstListaDValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPregledDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledDActionPerformed
        if(lstListaD.getSelectedValue() == null || lstListaD.getSelectedValue().equals(null)) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite željenog djelatnika!","Upozorenje",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        obradaD.setEntitet(lstListaD.getSelectedValue());
        var s = obradaD.getEntitet();
        dp = new DjelatnikPregled(obradaD.getEntitet().getIme(), obradaD.getEntitet().getPrezime());
      dp.prikazi();

    }//GEN-LAST:event_btnPregledDActionPerformed

    private void btnUnosDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosDActionPerformed
      new DjelatnikUnos(lstListaD).setVisible(true);
    }//GEN-LAST:event_btnUnosDActionPerformed

    private void btnBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeActionPerformed
        if(lstListaD.getSelectedValuesList()==null
            || lstListaD.getSelectedValuesList().isEmpty()){
            JOptionPane.showMessageDialog(getRootPane(),
                "Prvo odaberite djelatnika za brisanje!");
            return;
        }
        
        obradaD.setEntitet(lstListaD.getSelectedValue());

        if(JOptionPane.showConfirmDialog(
            getRootPane(),
            "Želite li sigurno obrisati " + obradaD.getEntitet().getIme() + " " + obradaD.getEntitet().getPrezime()  + " ?",
            "Brisanje",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE)==JOptionPane.NO_OPTION){
        return;
        }

        try {
            obradaD.delete();
            lstListaD.repaint();
            //ucitaj();
        } catch (ZooException ex) {
            JOptionPane.showMessageDialog(
                getRootPane(),
                ex.getPoruka());
        }

    }//GEN-LAST:event_btnBrisanjeActionPerformed

    private void btnIzmjenaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjenaDActionPerformed
        if(lstListaD.getSelectedValue() == null || lstListaD.getSelectedValue().equals(null)) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite željenog djelatnika!","Upozorenje",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        obradaD.setEntitet(lstListaD.getSelectedValue());
        var s = obradaD.getEntitet();
        dpr = new DjelatnikPromjena(s.getIme(),s.getPrezime(),s.getIBAN(),s, lstListaD);
        dpr.prikazi();
        
        
        
    }//GEN-LAST:event_btnIzmjenaDActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanje;
    private javax.swing.JButton btnIzmjenaD;
    private javax.swing.JButton btnPregledD;
    private javax.swing.JButton btnPretragaD;
    private javax.swing.JButton btnUnosD;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Djelatnik> lstListaD;
    private javax.swing.JTextField txtPretragaD;
    // End of variables declaration//GEN-END:variables

    private void ucitajDjelatnike() {
        
        DefaultListModel<Djelatnik> d = new DefaultListModel<>();
        d.addAll(obradaD.read(txtPretragaD.getText()));
        lstListaD.setModel(d);
        lstListaD.repaint();
        
    }
}
