/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zoloskivrtapp.view;

import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import zoloskivrtapp.controller.ObradaZivotinja;
import zoloskivrtapp.model.Zivotinja;
import zoloskivrtapp.util.ZooException;

/**
 *
 * @author Igor
 */
public class ProzorZivotinje extends javax.swing.JFrame {
    private final ObradaZivotinja obradaZ = new ObradaZivotinja();
    private ZivotinjaPregled zp;
    private ZivotinjaPromjena zpr;
    

    /**
     * Creates new form ProzorZivotinje
     */
    public ProzorZivotinje() {
        initComponents();
        setTitle("Životinje");
        txtPretraga.requestFocus();

    }

    public ProzorZivotinje(ZivotinjaPregled zp) {
        initComponents();
        this.zp = zp;
        setTitle("Životinje");
        txtPretraga.requestFocus();
    }

    public ProzorZivotinje(ZivotinjaPromjena zpr) {
        initComponents();
        this.zpr = zpr;
        setTitle("Životinje");
        txtPretraga.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jColorChooser1 = new javax.swing.JColorChooser();
        jButton1 = new javax.swing.JButton();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLista = new javax.swing.JList<>();
        btnPretraga = new javax.swing.JButton();
        btnIzmjena = new javax.swing.JButton();
        btnPregled = new javax.swing.JButton();
        btnBrisanje = new javax.swing.JButton();
        btnUnos = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Povratak na izbornik");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtPretraga.setBackground(new java.awt.Color(207, 214, 221));
        txtPretraga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaActionPerformed(evt);
            }
        });
        txtPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPretragaKeyPressed(evt);
            }
        });

        lstLista.setBackground(new java.awt.Color(207, 214, 221));
        lstLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstLista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lstLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstListaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstLista);

        btnPretraga.setBackground(new java.awt.Color(255, 255, 0));
        btnPretraga.setText(" 🔍");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        btnIzmjena.setBackground(new java.awt.Color(255, 255, 0));
        btnIzmjena.setText("Izmjena ");
        btnIzmjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjenaActionPerformed(evt);
            }
        });

        btnPregled.setBackground(new java.awt.Color(255, 255, 0));
        btnPregled.setText("Pregled");
        btnPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledActionPerformed(evt);
            }
        });

        btnBrisanje.setBackground(new java.awt.Color(255, 255, 0));
        btnBrisanje.setText("Brisanje");
        btnBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeActionPerformed(evt);
            }
        });

        btnUnos.setBackground(new java.awt.Color(255, 255, 0));
        btnUnos.setText("Unos");
        btnUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretraga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIzmjena, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrisanje, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmjena, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrisanje, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPretragaActionPerformed

    private void btnUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosActionPerformed
    new ZivotinjaUnos(getObradaZ(),lstLista).setVisible(true);
    }//GEN-LAST:event_btnUnosActionPerformed

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        ucitaj();
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void txtPretragaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretragaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ucitaj();
        }
    }//GEN-LAST:event_txtPretragaKeyPressed

    private void btnPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledActionPerformed
        if (lstLista.getSelectedValue() == null || lstLista.getSelectedValue().equals(null)) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite željenu životinju!", "Upozorenje", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        obradaZ.setEntitet(lstLista.getSelectedValue());
        var s = obradaZ.getEntitet();
        LocalDate dR = s.getDatumRodenja().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dD = s.getDatumDolaska().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dS;
        if (s.getDatumSmrti() != null) {
            dS = s.getDatumSmrti().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        } else {
            dS = null;
        }
        zp = new ZivotinjaPregled(s.getIme(), s.getZivotinjskaVrsta(), s.getVrsta(), s.getDjelatnik(), dR, dD, dS);
        zp.prikazi();

    }//GEN-LAST:event_btnPregledActionPerformed

    private void lstListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstListaValueChanged
         if(evt.getValueIsAdjusting()){
            return;
        }
        if(lstLista.getSelectedValue()==null){
            return;
        }
    }//GEN-LAST:event_lstListaValueChanged

    private void btnBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeActionPerformed
        if (lstLista.getSelectedValuesList() == null
                || lstLista.getSelectedValuesList().isEmpty()) {
            JOptionPane.showMessageDialog(getRootPane(),
                    "Prvo odaberite životinju za brisanje!");
            return;
        }

        obradaZ.setEntitet(lstLista.getSelectedValue());

        if (JOptionPane.showConfirmDialog(
                getRootPane(),
                "Želite li sigurno obrisati " + obradaZ.getEntitet().getIme() + " " + "(" + obradaZ.getEntitet().getZivotinjskaVrsta() + ")" + "?",
                "Brisanje",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION) {
            return;
        }

        try {
            obradaZ.delete();
            lstLista.repaint();
            ucitaj();
        } catch (ZooException ex) {
            JOptionPane.showMessageDialog(
                    getRootPane(),
                    ex.getPoruka());
        }


    }//GEN-LAST:event_btnBrisanjeActionPerformed

    private void btnIzmjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjenaActionPerformed
        if (lstLista.getSelectedValue() == null || lstLista.getSelectedValue().equals(null)) {
            JOptionPane.showMessageDialog(getRootPane(), "Prvo odaberite željenu životinju!", "Upozorenje", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        obradaZ.setEntitet(lstLista.getSelectedValue());
        var s = obradaZ.getEntitet();
        LocalDate dR = s.getDatumRodenja().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dD = s.getDatumDolaska().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate dS;
        if (s.getDatumSmrti() != null) {
            dS = s.getDatumSmrti().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        } else {
            dS = null;
        }
        zpr = new ZivotinjaPromjena(dR, dD, dS, s ,getObradaZ(),lstLista);
        zpr.prikazi();

    }//GEN-LAST:event_btnIzmjenaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanje;
    private javax.swing.JButton btnIzmjena;
    private javax.swing.JButton btnPregled;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnUnos;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Zivotinja> lstLista;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void ucitaj() {

        DefaultListModel<Zivotinja> z = new DefaultListModel<>();
        z.addAll(obradaZ.read(txtPretraga.getText()));
        lstLista.setModel(z);
        lstLista.repaint();
    }

    public ObradaZivotinja getObradaZ() {
        return obradaZ;
    }
}
